# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to deploy the first NSX Appliance node. Also checks the node
# status
#
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - deploy_nsx_cluster_vars_s11.yml
  tasks:
    - name: deploy NSX Manager OVA
      vmware.ansible_for_nsxt.nsxt_deploy_ova:
        ovftool_path: "/usr/local/bin"
        datacenter: "{{ nsx_node1['datacenter'] }}"
        datastore: "{{ nsx_node1['datastore'] }}"
        portgroup: "{{ nsx_node1['portgroup'] }}"
        cluster: "{{ nsx_node1['cluster'] }}"
        vmname: "{{ nsx_node1['hostname'] }}"
        hostname: "{{ nsx_node1['hostname'] }}"
        dns_server: "{{ dns_server }}"
        dns_domain: "{{ domain }}"
        ntp_server: "{{ ntp_server }}"
        gateway: "{{ gateway }}"
        ip_address: "{{ nsx_node1['mgmt_ip'] }}"
        netmask: "{{ netmask }}"
        admin_password: "{{ nsx_password }}"
        cli_password: "{{ cli_password }}"
        ssh_enabled: True
        allow_ssh_root_login: True
        path_to_ova: "{{ nsx_ova_path }}"
        ova_file: "{{ nsx_ova }}"
        vcenter: "{{ compute_managers[0]['mgmt_ip'] }}"
        vcenter_user: "{{ compute_managers[0]['username'] }}"
        vcenter_passwd: "{{ compute_managers[0]['password'] }}"
        deployment_size: "medium"
        # Note: The role below is for NSX 2.5 and above. For prior
        # release, the role should be "nsx-manager nsx-controller"
        role: "NSX Manager"

    - name: Check manager status
      vmware.ansible_for_nsxt.nsxt_manager_status:
          hostname: "{{ nsx_node1['mgmt_ip'] }}"
          username: "{{ nsx_username }}"
          password: "{{ cli_password }}"
          validate_certs: "{{ validate_certs }}"
          wait_time: 20