
---

- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - deploy_nsx_cluster_vars_s11.yml
  tasks:
    - name: Add NSX License
      vmware.ansible_for_nsxt.nsxt_licenses:
          hostname: "{{ nsx_node1.mgmt_ip }}"
          username: "{{ nsx_username }}"
          password: "{{ cli_password }}"
          validate_certs: "{{ validate_certs }}"
          license_key: "{{ item.license_key }}"
          state: "{{ state }}"
      with_items:
        - "{{nsxt_licenses}}"